### ISSUE TITLE
main: repo-wide typecheck is broken and blocks pre-push

### ISSUE THREAD

**Issue by OpenCodeEngineer** [dzianisv/opencode#64]
## Summary
The fork's `main` branch is currently type-broken in `packages/opencode`, which makes the repo-level pre-push hook fail (`.husky/pre-push` runs `bun typecheck` from the repo root).

## Repro
- `cd packages/opencode && bun typecheck`
- or trigger `.husky/pre-push` from a branch based on `main`

## Current errors on `origin/main`
```text
src/cli/cmd/tui/app.tsx(760,44): error TS2339: Property 'upgrade' does not exist on type 'Global'.
src/cli/cmd/tui/component/dialog-provider.tsx(74,24): error TS2339: Property 'prompts' does not exist on type 'ProviderAuthMethod'.
src/cli/cmd/tui/component/dialog-provider.tsx(77,33): error TS2339: Property 'prompts' does not exist on type 'ProviderAuthMethod'.
src/cli/cmd/tui/component/dialog-provider.tsx(86,15): error TS2353: Object literal may only specify known properties, and 'inputs' does not exist in type '{ providerID: string; directory?: string | undefined; workspace?: string | undefined; method?: number | undefined; }'.
src/cli/cmd/tui/component/dialog-provider.tsx(283,43): error TS2339: Property 'prompts' does not exist on type 'ProviderAuthMethod'.
src/cli/cmd/tui/component/dialog-provider.tsx(301,44): error TS7006: Parameter 'x' implicitly has an 'any' type.
src/cli/cmd/tui/component/dialog-provider.tsx(306,45): error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'string | PromiseLike<string | null> | null'.
src/cli/cmd/upgrade.ts(61,39): error TS2339: Property 'stderr' does not exist on type 'create.result'.
src/cli/cmd/upgrade.ts(64,33): error TS2339: Property 'stderr' does not exist on type 'create.result'.
src/cli/upgrade.ts(20,29): error TS2339: Property 'getReleaseType' does not exist on type 'typeof Installation'.
src/storage/db.node.ts(2,25): error TS2307: Cannot find module 'drizzle-orm/node-sqlite' or its corresponding type declarations.
test/installation/installation.test.ts(47,23): error TS2339: Property 'layer' does not exist on type 'typeof Installation'.
...plus the remaining `Installation.Service` test errors.
```

## Bisect
I bisected the broken `main` line against the last good ancestor and found that this branch became type-broken at the first bad cherry-pick on `main`:
- first bad commit: `d7abbab2b` `fix(bash): spool output to disk instead of in-memory capping`

At that first bad commit, `packages/opencode` was already failing with:
```text
src/cli/cmd/tui/component/prompt/index.tsx(939,46): error TS2339: Property 'text' does not exist on type 'PasteEvent'.
src/plugin/index.ts(14,54): error TS2307: Cannot find module '@gitlab/opencode-gitlab-auth' or its corresponding type declarations.
src/provider/provider.ts(43,66): error TS2307: Cannot find module '@gitlab/gitlab-ai-provider' or its corresponding type declarations.
```

So the current hook failure is not caused by the recent sidebar fix; the `main` line has been inconsistent since the start of this cherry-picked branch history.

## Goal
Restore a coherent `main` snapshot where:
- `cd packages/opencode && bun typecheck` passes
- root `bun typecheck` passes
- `.husky/pre-push` no longer blocks valid branches based on `main`
